name: update-patch-files
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"
jobs:
  update-patch-files:
    name: update-patch-files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update patch files
        uses: jayree/updatefilesbot@v1
        with:
          GitHubAppId: ${{ secrets.GitHubAppId }}
          GitHubAppPrivateKey: ${{ secrets.GitHubAppPrivateKey }}
